---
sudo: required

services:
  - docker

env:
  global:
    - container_id: ansible-container
    - distribution: ubuntu-docker-base
    - ansible_user: ubuntu

before_install:
  - 'sudo docker build --no-cache --rm --file=Dockerfile --tag=${distribution}:ansible .'

script:
  - 'sudo docker run --name ${container_id} --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro ${distribution}:ansible'
  - 'sudo docker exec --user ${ansible_user} "${container_id}" env ANSIBLE_FORCE_COLOR=1 ansible-playbook --version'
